### ISSUE TITLE
每天动态任务需要运行两次才能完成

### ISSUE THREAD

**Issue by 1314520lovelsc** [XiaoMengXinX/Fuck163MusicTasks#14]
每天三次动态任务需要运行两次脚本才能完成，用的是Linux环境

**Comment by XiaoMengXinX** [comment]
确认在配置文件中填写不同的发布动态文本了吗？如果连续发送多次相同内容的动态是会被网易云忽略的。

**Comment by 1314520lovelsc** [comment]
> 确认在配置文件中填写不同的发布动态文本了吗？如果连续发送多次相同内容的动态是会被网易云忽略的。
只加了两条，我改成三条试试
