### ISSUE TITLE
这个怎么用小白一个，抓紧出个云函数吧🌚

### ISSUE THREAD

**Issue by q1662352474** [XiaoMengXinX/Fuck163MusicTasks#15]

**Comment by XiaoMengXinX** [comment]
看了下，不太行，云函数要引用腾讯云自己的package（

**Comment by XiaoMengXinX** [comment]
最近有个Python的同类项目，有需求可以用那个

**Comment by sxceocom** [comment]
青龙面板可以用吗

**Comment by XiaoMengXinX** [comment]
> 青龙面板可以用吗

https://github.com/XiaoMengXinX/Fuck163MusicTasks/issues/4

**Comment by sxceocom** [comment]
感谢老铁！

**Comment by XiaoMengXinX** [comment]
详细一点的可以看 https://t.me/Music163bot_group/533

**Comment by XiaoMengXinX** [comment]
> 感谢老铁！

详细一点的可以看 https://t.me/Music163bot_group/533
