### ISSUE TITLE
可以完成黑胶成长值的任务吗，

### ISSUE THREAD

**Issue by YYplus** [XiaoMengXinX/Fuck163MusicTasks#2]

**Comment by XiaoMengXinX** [comment]
不能（
如果有需求的话 下周末我去写一下

**Comment by YYplus** [comment]
谢谢，能升级一下等级还是挺不错的

**Comment by XiaoMengXinX** [comment]
研究了一下，黑胶成长值相关的API没问题，但是不清楚网易云是怎么记录VIP任务中的三首歌曲的

也就是说只能加一个每日自动领取成长值，做任务暂时不太课呢鞥（

**Comment by XiaoMengXinX** [comment]
https://github.com/XiaoMengXinX/Fuck163MusicTasks/releases/tag/v2.1.2
更新了（
但是目前只能领取成长值，任务还得手动做

**Comment by YYplus** [comment]
好的，谢谢
