### ISSUE TITLE
访问自己的云圈任务

### ISSUE THREAD

**Issue by mayjack0312** [XiaoMengXinX/Fuck163MusicTasks#23]
大佬可以增加访问自己的云圈这个任务吗，貌似任务里就这个没涉及到了。OwO

**Comment by XiaoMengXinX** [comment]
@mayjack0312 这个任务是有的呀

**Comment by XiaoMengXinX** [comment]
@mayjack0312 readme没更新抱歉（

**Comment by XiaoMengXinX** [comment]
@mayjack0312 https://github.com/XiaoMengXinX/Fuck163MusicTasks/commit/2a46d445da98d89b72066a5259b1982c82eb21d9

**Comment by mayjack0312** [comment]
(๑‾ ꇴ ‾๑)好哒，谢谢大佬，我去看看 ~_~
