### ISSUE TITLE
青龙运行的一些小问题整理

### ISSUE THREAD

**Issue by mayjack0312** [XiaoMengXinX/Fuck163MusicTasks#24]
一、目前青龙貌似还没有加入访问个人云圈的任务
二、现在用青龙运行项目一天大概需要运行三次才能跑完所有任务
> 基本上第一次是日常任务，第二次是mlog任务（访问云圈任务好像是失败了），第三次运行才能把任务全做完（访问云圈）

- 这是我的运行log

```
第一次运行：
2022/05/28 00:17:08 [INFO] [XXX] 签到成功 (Android) (main.go:330)
2022/05/28 00:17:08 [INFO] [XXX] 重复签到 (web/PC) (main.go:338)
2022/05/28 00:17:09 [INFO] [XXX] 账号当前云豆数: 233 (main.go:570)
2022/05/28 00:17:09 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
2022/05/28 00:17:09 [INFO] [XXX] 任务「发布动态」任务未完成或进行中 (main.go:596)
2022/05/28 00:17:09 [INFO] [XXX] 「访问自己的云圈」任务已完成, 正在领取云豆 (main.go:584)
2022/05/28 00:17:09 [INFO] [XXX] 领取「访问自己的云圈」任务云豆成功, 云豆+2 (main.go:591)
2022/05/28 00:17:09 [INFO] [XXX] 任务「发布mlog」任务未完成或进行中 (main.go:596)
2022/05/28 00:17:09 [INFO] [XXX] 任务「回复粉丝私信」任务未完成或进行中 (main.go:596)
2022/05/28 00:17:09 [INFO] [XXX] 任务「音乐人中心签到」任务未完成或进行中 (main.go:596)
2022/05/28 00:17:19 [INFO] [XXX] 账号当前云豆数: 235 (main.go:628)
2022/05/28 00:17:19 [INFO] [XXX] 正在完成音乐人任务中 (main.go:213)
2022/05/28 00:17:19 [INFO] [XXX] 执行发送动态任务中 (main.go:254)
2022/05/28 00:17:19 [INFO] [XXX] 发送动态成功, 动态ID: xxxxxxxxxxx, 内容: "xxxxxxxxxxxxxxxxxxxxxx" (main.go:357)
2022/05/28 00:17:19 [INFO] [XXX] 延时 89 秒 (main.go:362)
2022/05/28 00:18:48 [INFO] [XXX] 删除动态成功, 动态ID: xxxxxxxxxxx (main.go:373)
2022/05/28 00:18:48 [INFO] [XXX] 延时 35 秒 (main.go:381)
2022/05/28 00:19:23 [INFO] [XXX] 发送动态任务执行完成 (main.go:259)
2022/05/28 00:19:23 [INFO] [XXX] 执行发送 Mlog 任务中 (main.go:281)
2022/05/28 00:19:23 [INFO] image: unknown format (main.go:284)
2022/05/28 00:19:23 [INFO] [XXX] 发送 Mlog 任务执行完成 (main.go:286)
2022/05/28 00:19:23 [INFO] [XXX] 执行发送私信任务中 (main.go:274)
2022/05/28 00:19:24 [INFO] [XXX] 发送私信成功, 用户ID: xxxxxxxxxxx, 内容: "xxxxxxxxxxxxxxxxxxxxxx" (main.go:456)
2022/05/28 00:19:24 [INFO] [XXX] 延时 15 秒 (main.go:468)
2022/05/28 00:19:39 [INFO] [XXX] 发送私信成功, 用户ID: xxxxxxxxxxx, 内容: "xxxxxxxxxxxxxxxxxxxxxx" (main.go:456)
2022/05/28 00:19:39 [INFO] [XXX] 延时 9 秒 (main.go:468)
2022/05/28 00:19:48 [INFO] [XXX] 发送私信任务执行完成 (main.go:279)
2022/05/28 00:19:48 [INFO] [XXX] 执行音乐人签到任务中 (main.go:243)
2022/05/28 00:19:48 [INFO] [XXX] 音乐人签到成功 (main.go:249)
2022/05/28 00:19:48 [INFO] [XXX] 音乐人任务执行完成, 正在重新检查并领取云豆 (main.go:217)
2022/05/28 00:19:58 [INFO] [XXX] 账号当前云豆数: 235 (main.go:570)
2022/05/28 00:19:58 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
2022/05/28 00:19:58 [INFO] [XXX] 「发布动态」任务已完成, 正在领取云豆 (main.go:584)
2022/05/28 00:19:58 [INFO] [XXX] 领取「发布动态」任务云豆成功, 云豆+3 (main.go:591)
2022/05/28 00:19:58 [INFO] [XXX] 任务「发布mlog」任务未完成或进行中 (main.go:596)
2022/05/28 00:19:58 [INFO] [XXX] 「回复粉丝私信」任务已完成, 正在领取云豆 (main.go:584)
2022/05/28 00:19:58 [INFO] [XXX] 领取「回复粉丝私信」任务云豆成功, 云豆+2 (main.go:591)
2022/05/28 00:19:58 [INFO] [XXX] 「音乐人中心签到」任务已完成, 正在领取云豆 (main.go:584)
2022/05/28 00:19:58 [INFO] [XXX] 领取「音乐人中心签到」任务云豆成功, 云豆+1 (main.go:591)
2022/05/28 00:20:08 [INFO] [XXX] 账号当前云豆数: 241 (main.go:628)
2022/05/28 00:20:08 [INFO] [XXX] 正在检查会员状态 (main.go:551)
2022/05/28 00:20:08 [INFO] [XXX] 检查成功，正在领取会员任务成长值 (main.go:560)
第二次运行：
2022/05/28 00:24:06 [INFO] [XXX] 签到成功 (Android) (main.go:330)
2022/05/28 00:24:06 [INFO] [XXX] 重复签到 (web/PC) (main.go:338)
2022/05/28 00:24:06 [INFO] [XXX] 账号当前云豆数: 241 (main.go:570)
2022/05/28 00:24:06 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
2022/05/28 00:24:07 [INFO] [XXX] 任务「发布mlog」任务未完成或进行中 (main.go:596)
2022/05/28 00:24:07 [INFO] [XXX] 正在完成音乐人任务中 (main.go:213)
2022/05/28 00:24:07 [INFO] [XXX] 执行发送 Mlog 任务中 (main.go:281)
2022/05/28 00:24:07 [INFO] image: unknown format (main.go:284)
2022/05/28 00:24:07 [INFO] [XXX] 发送 Mlog 任务执行完成 (main.go:286)
2022/05/28 00:24:07 [INFO] [XXX] 音乐人任务执行完成, 正在重新检查并领取云豆 (main.go:217)
2022/05/28 00:24:17 [INFO] [XXX] 账号当前云豆数: 241 (main.go:570)
2022/05/28 00:24:17 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
2022/05/28 00:24:17 [INFO] [XXX] 任务「发布mlog」任务未完成或进行中 (main.go:596)
2022/05/28 00:24:17 [INFO] [XXX] 正在检查会员状态 (main.go:551)
2022/05/28 00:24:17 [INFO] [XXX] 检查成功，正在领取会员任务成长值 (main.go:560)
第三次运行：
2022/05/28 00:24:25 [INFO] [XXX] 签到成功 (Android) (main.go:330)
2022/05/28 00:24:25 [INFO] [XXX] 重复签到 (web/PC) (main.go:338)
2022/05/28 00:24:25 [INFO] [XXX] 账号当前云豆数: 241 (main.go:570)
2022/05/28 00:24:25 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
2022/05/28 00:24:25 [INFO] [XXX] 任务「发布mlog」任务未完成或进行中 (main.go:596)
2022/05/28 00:24:25 [INFO] [XXX] 正在完成音乐人任务中 (main.go:213)
2022/05/28 00:24:25 [INFO] [XXX] 执行发送 Mlog 任务中 (main.go:281)
2022/05/28 00:24:26 [INFO] [XXX] 发送 Mlog 成功, 动态ID: xxxxxxxxxxx, 内容: "xxxxxxxxxxxxxxxxxxxxxx", 图片: "xxxxxxxxxxx.jpg" (main.go:497)
2022/05/28 00:24:26 [INFO] [XXX] 删除 Mlog 成功, 动态ID: xxxxxxxxxxx (main.go:511)
2022/05/28 00:24:26 [INFO] [XXX] 发送 Mlog 任务执行完成 (main.go:286)
2022/05/28 00:24:26 [INFO] [XXX] 音乐人任务执行完成, 正在重新检查并领取云豆 (main.go:217)
2022/05/28 00:24:36 [INFO] [XXX] 账号当前云豆数: 241 (main.go:570)
2022/05/28 00:24:36 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
2022/05/28 00:24:36 [INFO] [XXX] 「发布mlog」任务已完成, 正在领取云豆 (main.go:584)
2022/05/28 00:24:36 [INFO] [XXX] 领取「发布mlog」任务云豆成功, 云豆+5 (main.go:591)
2022/05/28 00:24:47 [INFO] [XXX] 账号当前云豆数: 246 (main.go:628)
2022/05/28 00:24:47 [INFO] [XXX] 后面的任务, 明天再来探索吧！ (main.go:631)
2022/05/28 00:24:47 [INFO] [XXX] 正在检查会员状态 (main.go:551)
2022/05/28 00:24:47 [INFO] [XXX] 检查成功，正在领取会员任务成长值 (main.go:560)
```

**Comment by mayjack0312** [comment]
这里访问云圈是手动的 ~_~

**Comment by XiaoMengXinX** [comment]
访问云圈的问题我再看看吧，按理说是没问题的

**Comment by mayjack0312** [comment]
图片我看文件夹里了 都没变化
第一次运行不行，只能再跑一遍才显示成功（明天我再试试）
(๑‾ ꇴ ‾๑) 好哒 谢谢大佬
云圈那个我去看main.go了，里面没有给相关的config.json的变量
我不知道是程序逻辑直接跑还是由于没加变量导致的 go我也是刚研究两三天OwO
以前我用的是直接给的变量，然后去config里加变量：到云圈ID
然后才跑起来的

**Comment by XiaoMengXinX** [comment]
```
2022/05/28 00:50:13 [INFO] [xxx] 账号当前云豆数: 1854 (main.go:570)
2022/05/28 00:50:13 [INFO] [xxx] 获取音乐人任务中... (main.go:571)
2022/05/28 00:50:13 [INFO] [xxx] 任务「发布动态」任务未完成或进行中 (main.go:596)
2022/05/28 00:50:13 [INFO] [xxx] 任务「访问自己的云圈」任务未完成或进行中 (main.go:596)
2022/05/28 00:50:13 [INFO] [xxx] 任务「发布mlog」任务未完成或进行中 (main.go:596)
2022/05/28 00:50:13 [INFO] [xxx] 任务「回复粉丝私信」任务未完成或进行中 (main.go:596)
2022/05/28 00:50:13 [INFO] [xxx] 任务「音乐人中心签到」任务未完成或进行中 (main.go:596)

2022/05/28 00:51:24 [INFO] [xxx] 执行访问云圈任务中 (main.go:300)
2022/05/28 00:51:24 [INFO] [xxx] 访问云圈任务执行完成 (main.go:305)

2022/05/28 00:52:44 [INFO] [xxx] 「访问自己的云圈」任务已完成, 正在领取云豆 (main.go:584)
2022/05/28 00:52:44 [INFO] [xxx] 领取「访问自己的云圈」任务云豆成功, 云豆+2 (main.go:591)
```
访问云圈我这里是可以的

**Comment by mayjack0312** [comment]
您的config.json没变化吧
我config.json还停留在您readme上

**Comment by XiaoMengXinX** [comment]
> 图片我看文件夹里了 都没变化 第一次运行不行，只能再跑一遍才显示成功（明天我再试试） (๑‾ ꇴ ‾๑) 好哒 谢谢大佬 云圈那个我去看main.go了，里面没有给相关的config.json的变量 我不知道是程序逻辑直接跑还是由于没加变量导致的 go我也是刚研究两三天OwO 以前我用的是直接给的变量，然后去config里加变量：到云圈ID 然后才跑起来的

云圈ID是自动获取的，如果音乐人账号下有云圈就会自动访问自己的云圈

**Comment by XiaoMengXinX** [comment]
config里不需要加东西 云圈任务没做开关

**Comment by mayjack0312** [comment]
可能和运行时间也有关系，前几天我都基本上是晚上12:05-12:10运行的
今天我是上午9:30运行的
前面的那几个错误基本都没有了
只有个人云圈还是需要手动做一下才成功

**Comment by 18684729182** [comment]
> 一、目前青龙貌似还没有加入访问个人云圈的任务 二、现在用青龙运行项目一天大概需要运行三次才能跑完所有任务
> 
> > 基本上第一次是日常任务，第二次是mlog任务（访问云圈任务好像是失败了），第三次运行才能把任务全做完（访问云圈）
> 
> * 这是我的运行log
> 
> ```
> 第一次运行：
> 2022/05/28 00:17:08 [INFO] [XXX] 签到成功 (Android) (main.go:330)
> 2022/05/28 00:17:08 [INFO] [XXX] 重复签到 (web/PC) (main.go:338)
> 2022/05/28 00:17:09 [INFO] [XXX] 账号当前云豆数: 233 (main.go:570)
> 2022/05/28 00:17:09 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
> 2022/05/28 00:17:09 [INFO] [XXX] 任务「发布动态」任务未完成或进行中 (main.go:596)
> 2022/05/28 00:17:09 [INFO] [XXX] 「访问自己的云圈」任务已完成, 正在领取云豆 (main.go:584)
> 2022/05/28 00:17:09 [INFO] [XXX] 领取「访问自己的云圈」任务云豆成功, 云豆+2 (main.go:591)
> 2022/05/28 00:17:09 [INFO] [XXX] 任务「发布mlog」任务未完成或进行中 (main.go:596)
> 2022/05/28 00:17:09 [INFO] [XXX] 任务「回复粉丝私信」任务未完成或进行中 (main.go:596)
> 2022/05/28 00:17:09 [INFO] [XXX] 任务「音乐人中心签到」任务未完成或进行中 (main.go:596)
> 2022/05/28 00:17:19 [INFO] [XXX] 账号当前云豆数: 235 (main.go:628)
> 2022/05/28 00:17:19 [INFO] [XXX] 正在完成音乐人任务中 (main.go:213)
> 2022/05/28 00:17:19 [INFO] [XXX] 执行发送动态任务中 (main.go:254)
> 2022/05/28 00:17:19 [INFO] [XXX] 发送动态成功, 动态ID: xxxxxxxxxxx, 内容: "xxxxxxxxxxxxxxxxxxxxxx" (main.go:357)
> 2022/05/28 00:17:19 [INFO] [XXX] 延时 89 秒 (main.go:362)
> 2022/05/28 00:18:48 [INFO] [XXX] 删除动态成功, 动态ID: xxxxxxxxxxx (main.go:373)
> 2022/05/28 00:18:48 [INFO] [XXX] 延时 35 秒 (main.go:381)
> 2022/05/28 00:19:23 [INFO] [XXX] 发送动态任务执行完成 (main.go:259)
> 2022/05/28 00:19:23 [INFO] [XXX] 执行发送 Mlog 任务中 (main.go:281)
> 2022/05/28 00:19:23 [INFO] image: unknown format (main.go:284)
> 2022/05/28 00:19:23 [INFO] [XXX] 发送 Mlog 任务执行完成 (main.go:286)
> 2022/05/28 00:19:23 [INFO] [XXX] 执行发送私信任务中 (main.go:274)
> 2022/05/28 00:19:24 [INFO] [XXX] 发送私信成功, 用户ID: xxxxxxxxxxx, 内容: "xxxxxxxxxxxxxxxxxxxxxx" (main.go:456)
> 2022/05/28 00:19:24 [INFO] [XXX] 延时 15 秒 (main.go:468)
> 2022/05/28 00:19:39 [INFO] [XXX] 发送私信成功, 用户ID: xxxxxxxxxxx, 内容: "xxxxxxxxxxxxxxxxxxxxxx" (main.go:456)
> 2022/05/28 00:19:39 [INFO] [XXX] 延时 9 秒 (main.go:468)
> 2022/05/28 00:19:48 [INFO] [XXX] 发送私信任务执行完成 (main.go:279)
> 2022/05/28 00:19:48 [INFO] [XXX] 执行音乐人签到任务中 (main.go:243)
> 2022/05/28 00:19:48 [INFO] [XXX] 音乐人签到成功 (main.go:249)
> 2022/05/28 00:19:48 [INFO] [XXX] 音乐人任务执行完成, 正在重新检查并领取云豆 (main.go:217)
> 2022/05/28 00:19:58 [INFO] [XXX] 账号当前云豆数: 235 (main.go:570)
> 2022/05/28 00:19:58 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
> 2022/05/28 00:19:58 [INFO] [XXX] 「发布动态」任务已完成, 正在领取云豆 (main.go:584)
> 2022/05/28 00:19:58 [INFO] [XXX] 领取「发布动态」任务云豆成功, 云豆+3 (main.go:591)
> 2022/05/28 00:19:58 [INFO] [XXX] 任务「发布mlog」任务未完成或进行中 (main.go:596)
> 2022/05/28 00:19:58 [INFO] [XXX] 「回复粉丝私信」任务已完成, 正在领取云豆 (main.go:584)
> 2022/05/28 00:19:58 [INFO] [XXX] 领取「回复粉丝私信」任务云豆成功, 云豆+2 (main.go:591)
> 2022/05/28 00:19:58 [INFO] [XXX] 「音乐人中心签到」任务已完成, 正在领取云豆 (main.go:584)
> 2022/05/28 00:19:58 [INFO] [XXX] 领取「音乐人中心签到」任务云豆成功, 云豆+1 (main.go:591)
> 2022/05/28 00:20:08 [INFO] [XXX] 账号当前云豆数: 241 (main.go:628)
> 2022/05/28 00:20:08 [INFO] [XXX] 正在检查会员状态 (main.go:551)
> 2022/05/28 00:20:08 [INFO] [XXX] 检查成功，正在领取会员任务成长值 (main.go:560)
> 第二次运行：
> 2022/05/28 00:24:06 [INFO] [XXX] 签到成功 (Android) (main.go:330)
> 2022/05/28 00:24:06 [INFO] [XXX] 重复签到 (web/PC) (main.go:338)
> 2022/05/28 00:24:06 [INFO] [XXX] 账号当前云豆数: 241 (main.go:570)
> 2022/05/28 00:24:06 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
> 2022/05/28 00:24:07 [INFO] [XXX] 任务「发布mlog」任务未完成或进行中 (main.go:596)
> 2022/05/28 00:24:07 [INFO] [XXX] 正在完成音乐人任务中 (main.go:213)
> 2022/05/28 00:24:07 [INFO] [XXX] 执行发送 Mlog 任务中 (main.go:281)
> 2022/05/28 00:24:07 [INFO] image: unknown format (main.go:284)
> 2022/05/28 00:24:07 [INFO] [XXX] 发送 Mlog 任务执行完成 (main.go:286)
> 2022/05/28 00:24:07 [INFO] [XXX] 音乐人任务执行完成, 正在重新检查并领取云豆 (main.go:217)
> 2022/05/28 00:24:17 [INFO] [XXX] 账号当前云豆数: 241 (main.go:570)
> 2022/05/28 00:24:17 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
> 2022/05/28 00:24:17 [INFO] [XXX] 任务「发布mlog」任务未完成或进行中 (main.go:596)
> 2022/05/28 00:24:17 [INFO] [XXX] 正在检查会员状态 (main.go:551)
> 2022/05/28 00:24:17 [INFO] [XXX] 检查成功，正在领取会员任务成长值 (main.go:560)
> 第三次运行：
> 2022/05/28 00:24:25 [INFO] [XXX] 签到成功 (Android) (main.go:330)
> 2022/05/28 00:24:25 [INFO] [XXX] 重复签到 (web/PC) (main.go:338)
> 2022/05/28 00:24:25 [INFO] [XXX] 账号当前云豆数: 241 (main.go:570)
> 2022/05/28 00:24:25 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
> 2022/05/28 00:24:25 [INFO] [XXX] 任务「发布mlog」任务未完成或进行中 (main.go:596)
> 2022/05/28 00:24:25 [INFO] [XXX] 正在完成音乐人任务中 (main.go:213)
> 2022/05/28 00:24:25 [INFO] [XXX] 执行发送 Mlog 任务中 (main.go:281)
> 2022/05/28 00:24:26 [INFO] [XXX] 发送 Mlog 成功, 动态ID: xxxxxxxxxxx, 内容: "xxxxxxxxxxxxxxxxxxxxxx", 图片: "xxxxxxxxxxx.jpg" (main.go:497)
> 2022/05/28 00:24:26 [INFO] [XXX] 删除 Mlog 成功, 动态ID: xxxxxxxxxxx (main.go:511)
> 2022/05/28 00:24:26 [INFO] [XXX] 发送 Mlog 任务执行完成 (main.go:286)
> 2022/05/28 00:24:26 [INFO] [XXX] 音乐人任务执行完成, 正在重新检查并领取云豆 (main.go:217)
> 2022/05/28 00:24:36 [INFO] [XXX] 账号当前云豆数: 241 (main.go:570)
> 2022/05/28 00:24:36 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
> 2022/05/28 00:24:36 [INFO] [XXX] 「发布mlog」任务已完成, 正在领取云豆 (main.go:584)
> 2022/05/28 00:24:36 [INFO] [XXX] 领取「发布mlog」任务云豆成功, 云豆+5 (main.go:591)
> 2022/05/28 00:24:47 [INFO] [XXX] 账号当前云豆数: 246 (main.go:628)
> 2022/05/28 00:24:47 [INFO] [XXX] 后面的任务, 明天再来探索吧！ (main.go:631)
> 2022/05/28 00:24:47 [INFO] [XXX] 正在检查会员状态 (main.go:551)
> 2022/05/28 00:24:47 [INFO] [XXX] 检查成功，正在领取会员任务成长值 (main.go:560)
> ```
请问一下现在还能使用不，求一个青龙部署的教程

**Comment by XiaoMengXinX** [comment]
您是不是把任务间的延迟都关掉了

**Comment by mayjack0312** [comment]
> 您是不是把任务间的延迟都关掉了

没关掉，任务之间还是有100~200s的延迟的

**Comment by mayjack0312** [comment]
> > 一、目前青龙貌似还没有加入访问个人云圈的任务 二、现在用青龙运行项目一天大概需要运行三次才能跑完所有任务
> > > 基本上第一次是日常任务，第二次是mlog任务（访问云圈任务好像是失败了），第三次运行才能把任务全做完（访问云圈）
> > 
> > 
> > 
> > * 这是我的运行log
> > 
> > ```
> > 第一次运行：
> > 2022/05/28 00:17:08 [INFO] [XXX] 签到成功 (Android) (main.go:330)
> > 2022/05/28 00:17:08 [INFO] [XXX] 重复签到 (web/PC) (main.go:338)
> > 2022/05/28 00:17:09 [INFO] [XXX] 账号当前云豆数: 233 (main.go:570)
> > 2022/05/28 00:17:09 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
> > 2022/05/28 00:17:09 [INFO] [XXX] 任务「发布动态」任务未完成或进行中 (main.go:596)
> > 2022/05/28 00:17:09 [INFO] [XXX] 「访问自己的云圈」任务已完成, 正在领取云豆 (main.go:584)
> > 2022/05/28 00:17:09 [INFO] [XXX] 领取「访问自己的云圈」任务云豆成功, 云豆+2 (main.go:591)
> > 2022/05/28 00:17:09 [INFO] [XXX] 任务「发布mlog」任务未完成或进行中 (main.go:596)
> > 2022/05/28 00:17:09 [INFO] [XXX] 任务「回复粉丝私信」任务未完成或进行中 (main.go:596)
> > 2022/05/28 00:17:09 [INFO] [XXX] 任务「音乐人中心签到」任务未完成或进行中 (main.go:596)
> > 2022/05/28 00:17:19 [INFO] [XXX] 账号当前云豆数: 235 (main.go:628)
> > 2022/05/28 00:17:19 [INFO] [XXX] 正在完成音乐人任务中 (main.go:213)
> > 2022/05/28 00:17:19 [INFO] [XXX] 执行发送动态任务中 (main.go:254)
> > 2022/05/28 00:17:19 [INFO] [XXX] 发送动态成功, 动态ID: xxxxxxxxxxx, 内容: "xxxxxxxxxxxxxxxxxxxxxx" (main.go:357)
> > 2022/05/28 00:17:19 [INFO] [XXX] 延时 89 秒 (main.go:362)
> > 2022/05/28 00:18:48 [INFO] [XXX] 删除动态成功, 动态ID: xxxxxxxxxxx (main.go:373)
> > 2022/05/28 00:18:48 [INFO] [XXX] 延时 35 秒 (main.go:381)
> > 2022/05/28 00:19:23 [INFO] [XXX] 发送动态任务执行完成 (main.go:259)
> > 2022/05/28 00:19:23 [INFO] [XXX] 执行发送 Mlog 任务中 (main.go:281)
> > 2022/05/28 00:19:23 [INFO] image: unknown format (main.go:284)
> > 2022/05/28 00:19:23 [INFO] [XXX] 发送 Mlog 任务执行完成 (main.go:286)
> > 2022/05/28 00:19:23 [INFO] [XXX] 执行发送私信任务中 (main.go:274)
> > 2022/05/28 00:19:24 [INFO] [XXX] 发送私信成功, 用户ID: xxxxxxxxxxx, 内容: "xxxxxxxxxxxxxxxxxxxxxx" (main.go:456)
> > 2022/05/28 00:19:24 [INFO] [XXX] 延时 15 秒 (main.go:468)
> > 2022/05/28 00:19:39 [INFO] [XXX] 发送私信成功, 用户ID: xxxxxxxxxxx, 内容: "xxxxxxxxxxxxxxxxxxxxxx" (main.go:456)
> > 2022/05/28 00:19:39 [INFO] [XXX] 延时 9 秒 (main.go:468)
> > 2022/05/28 00:19:48 [INFO] [XXX] 发送私信任务执行完成 (main.go:279)
> > 2022/05/28 00:19:48 [INFO] [XXX] 执行音乐人签到任务中 (main.go:243)
> > 2022/05/28 00:19:48 [INFO] [XXX] 音乐人签到成功 (main.go:249)
> > 2022/05/28 00:19:48 [INFO] [XXX] 音乐人任务执行完成, 正在重新检查并领取云豆 (main.go:217)
> > 2022/05/28 00:19:58 [INFO] [XXX] 账号当前云豆数: 235 (main.go:570)
> > 2022/05/28 00:19:58 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
> > 2022/05/28 00:19:58 [INFO] [XXX] 「发布动态」任务已完成, 正在领取云豆 (main.go:584)
> > 2022/05/28 00:19:58 [INFO] [XXX] 领取「发布动态」任务云豆成功, 云豆+3 (main.go:591)
> > 2022/05/28 00:19:58 [INFO] [XXX] 任务「发布mlog」任务未完成或进行中 (main.go:596)
> > 2022/05/28 00:19:58 [INFO] [XXX] 「回复粉丝私信」任务已完成, 正在领取云豆 (main.go:584)
> > 2022/05/28 00:19:58 [INFO] [XXX] 领取「回复粉丝私信」任务云豆成功, 云豆+2 (main.go:591)
> > 2022/05/28 00:19:58 [INFO] [XXX] 「音乐人中心签到」任务已完成, 正在领取云豆 (main.go:584)
> > 2022/05/28 00:19:58 [INFO] [XXX] 领取「音乐人中心签到」任务云豆成功, 云豆+1 (main.go:591)
> > 2022/05/28 00:20:08 [INFO] [XXX] 账号当前云豆数: 241 (main.go:628)
> > 2022/05/28 00:20:08 [INFO] [XXX] 正在检查会员状态 (main.go:551)
> > 2022/05/28 00:20:08 [INFO] [XXX] 检查成功，正在领取会员任务成长值 (main.go:560)
> > 第二次运行：
> > 2022/05/28 00:24:06 [INFO] [XXX] 签到成功 (Android) (main.go:330)
> > 2022/05/28 00:24:06 [INFO] [XXX] 重复签到 (web/PC) (main.go:338)
> > 2022/05/28 00:24:06 [INFO] [XXX] 账号当前云豆数: 241 (main.go:570)
> > 2022/05/28 00:24:06 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
> > 2022/05/28 00:24:07 [INFO] [XXX] 任务「发布mlog」任务未完成或进行中 (main.go:596)
> > 2022/05/28 00:24:07 [INFO] [XXX] 正在完成音乐人任务中 (main.go:213)
> > 2022/05/28 00:24:07 [INFO] [XXX] 执行发送 Mlog 任务中 (main.go:281)
> > 2022/05/28 00:24:07 [INFO] image: unknown format (main.go:284)
> > 2022/05/28 00:24:07 [INFO] [XXX] 发送 Mlog 任务执行完成 (main.go:286)
> > 2022/05/28 00:24:07 [INFO] [XXX] 音乐人任务执行完成, 正在重新检查并领取云豆 (main.go:217)
> > 2022/05/28 00:24:17 [INFO] [XXX] 账号当前云豆数: 241 (main.go:570)
> > 2022/05/28 00:24:17 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
> > 2022/05/28 00:24:17 [INFO] [XXX] 任务「发布mlog」任务未完成或进行中 (main.go:596)
> > 2022/05/28 00:24:17 [INFO] [XXX] 正在检查会员状态 (main.go:551)
> > 2022/05/28 00:24:17 [INFO] [XXX] 检查成功，正在领取会员任务成长值 (main.go:560)
> > 第三次运行：
> > 2022/05/28 00:24:25 [INFO] [XXX] 签到成功 (Android) (main.go:330)
> > 2022/05/28 00:24:25 [INFO] [XXX] 重复签到 (web/PC) (main.go:338)
> > 2022/05/28 00:24:25 [INFO] [XXX] 账号当前云豆数: 241 (main.go:570)
> > 2022/05/28 00:24:25 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
> > 2022/05/28 00:24:25 [INFO] [XXX] 任务「发布mlog」任务未完成或进行中 (main.go:596)
> > 2022/05/28 00:24:25 [INFO] [XXX] 正在完成音乐人任务中 (main.go:213)
> > 2022/05/28 00:24:25 [INFO] [XXX] 执行发送 Mlog 任务中 (main.go:281)
> > 2022/05/28 00:24:26 [INFO] [XXX] 发送 Mlog 成功, 动态ID: xxxxxxxxxxx, 内容: "xxxxxxxxxxxxxxxxxxxxxx", 图片: "xxxxxxxxxxx.jpg" (main.go:497)
> > 2022/05/28 00:24:26 [INFO] [XXX] 删除 Mlog 成功, 动态ID: xxxxxxxxxxx (main.go:511)
> > 2022/05/28 00:24:26 [INFO] [XXX] 发送 Mlog 任务执行完成 (main.go:286)
> > 2022/05/28 00:24:26 [INFO] [XXX] 音乐人任务执行完成, 正在重新检查并领取云豆 (main.go:217)
> > 2022/05/28 00:24:36 [INFO] [XXX] 账号当前云豆数: 241 (main.go:570)
> > 2022/05/28 00:24:36 [INFO] [XXX] 获取音乐人任务中... (main.go:571)
> > 2022/05/28 00:24:36 [INFO] [XXX] 「发布mlog」任务已完成, 正在领取云豆 (main.go:584)
> > 2022/05/28 00:24:36 [INFO] [XXX] 领取「发布mlog」任务云豆成功, 云豆+5 (main.go:591)
> > 2022/05/28 00:24:47 [INFO] [XXX] 账号当前云豆数: 246 (main.go:628)
> > 2022/05/28 00:24:47 [INFO] [XXX] 后面的任务, 明天再来探索吧！ (main.go:631)
> > 2022/05/28 00:24:47 [INFO] [XXX] 正在检查会员状态 (main.go:551)
> > 2022/05/28 00:24:47 [INFO] [XXX] 检查成功，正在领取会员任务成长值 (main.go:560)
> > ```
> 
> 请问一下现在还能使用不，求一个青龙部署的教程

群里置顶可以参考一下

**Comment by 18684729182** [comment]
> config里不需要加东西 云圈任务没做开关



> config里不需要加东西 云圈任务没做开关
go run *.go
2022/07/01 10:29:05 [ERROR] invalid character ':' after array element (main.go:115)
2022/07/01 10:29:05 [FATAL] 读取配置文件失败, 请检查你的 JSON 格式是否正确 (main.go:116)
exit status 
这个配置文件，我就改了MUSIC_U。其他的都是默认的，为啥提示配置错误
