### ISSUE TITLE
win amd tasks闪退问题

### ISSUE THREAD

**Issue by resetsix** [XiaoMengXinX/Fuck163MusicTasks#26]
笔记本是win amd的，打开amd的运行程序会闪退（打开arm是不兼容，这个理解）。请问闪退怎么办呀？json文件那些配置都是已经配置好的。求大佬解答。

**Comment by XiaoMengXinX** [comment]
@resetsix 您是直接双击打开的吗？

**Comment by resetsix** [comment]
> @resetsix 您是直接双击打开的吗？

在WindowsTerminal打开的

**Comment by XiaoMengXinX** [comment]
@resetsix 有日志吗？

**Comment by resetsix** [comment]
> @resetsix 有日志吗？

2022/07/25 10:40:28 [ERROR] open config.json: The system cannot find the file specified. (main.go:99)
2022/07/25 10:40:28 [FATAL] 读取配置文件失败 (main.go:100)
2022/07/25 10:41:01 [ERROR] open config.json: The system cannot find the file specified. (main.go:99)
2022/07/25 10:41:01 [FATAL] 读取配置文件失败 (main.go:100)
2022/07/25 11:16:38 [ERROR] open config.json: The system cannot find the file specified. (main.go:99)
2022/07/25 11:16:38 [FATAL] 读取配置文件失败 (main.go:100)
2022/07/25 11:19:35 [ERROR] open config.json: The system cannot find the file specified. (main.go:99)
2022/07/25 11:19:35 [FATAL] 读取配置文件失败 (main.go:100)

**Comment by XiaoMengXinX** [comment]
@resetsix 用 -c 参数指定一下配置文件目录试试

**Comment by resetsix** [comment]
> @resetsix 用 -c 参数指定一下配置文件目录试试

PS C:\Users\Admin\Desktop> .\Fuck163MusicTasks_windows_amd64.exe
2022/07/25 12:28:58 [ERROR] open config.json: The system cannot find the file specified. (main.go:99)
2022/07/25 12:28:58 [FATAL] 读取配置文件失败 (main.go:100)
PS C:\Users\Admin\Desktop> .\Fuck163MusicTasks_windows_amd64.exe -c
flag needs an argument: -c
Usage of C:\Users\Admin\Desktop\Fuck163MusicTasks_windows_amd64.exe:
  -c string
        Config filename (default "config.json")
  -d    DEBUG mode
  -v    Print version
PS C:\Users\Admin\Desktop> .\Fuck163MusicTasks_windows_amd64.exe -c
flag needs an argument: -c
Usage of C:\Users\Admin\Desktop\Fuck163MusicTasks_windows_amd64.exe:
  -c string
        Config filename (default "config.json")
  -d    DEBUG mode
  -v    Print version
PS C:\Users\Admin\Desktop> .\Fuck163MusicTasks_windows_amd64.exe - c
2022/07/25 12:30:15 [ERROR] open config.json: The system cannot find the file specified. (main.go:99)
2022/07/25 12:30:15 [FATAL] 读取配置文件失败 (main.go:100)
PS C:\Users\Admin\Desktop>


还是失败呢

**Comment by resetsix** [comment]
> @resetsix 用 -c 参数指定一下配置文件目录试试

抱歉，我的错，忘记把json文件跟exe放在同一目录了。好了，谢谢大佬
