### ISSUE TITLE
可以考虑增加一个推送

### ISSUE THREAD

**Issue by DumKing** [XiaoMengXinX/Fuck163MusicTasks#27]

**Comment by XiaoMengXinX** [comment]
@DumKing 例如？

**Comment by DumKing** [comment]
> @DumKing 例如？

@XiaoMengXinX 比如推送bark，推送企业微信/钉钉 或者自定义API

**Comment by XiaoMengXinX** [comment]
@DumKing 那用青龙就可以呀（

**Comment by DumKing** [comment]
不用青龙😔😔😔😔 我习惯直接部署服务器上  没写过go  而我需要推送到我自己搭建的api   有一种推送方式的模板代码我就可以自己定制我自己需要的 @XiaoMengXinX

**Comment by resetsix** [comment]
请问用青龙怎么推送？我在配置文件的config.sh、面板系统设置的通知设置里试了push，server，钉钉，可是脚本任务完成后就是不推送，token什么的都没问题，能会送新脚本，登录日志的信息，京豆的资产通知也能用，就是音乐人任务的通知没有。请问怎么办？
