### ISSUE TITLE
https？

### ISSUE THREAD

**Issue by gbxh** [XiaoMengXinX/Fuck163MusicTasks#29]
我执行时返回了下面的结果
`##***group***Run ./Fuck163MusicTasks_linux_amd64
***36;1m./Fuck163MusicTasks_linux_amd64***0m
shell: /usr/bin/bash -e ***0***
##***endgroup***
[2](https://github.com/gbxh/Fuck163MusicTasks-Action/actions/runs/3129232583/jobs/5078201480#step:4:2)022/09/26 16:09:18 ***ERROR*** Post "/login/status?timestamp=1664208558": unsupported protocol scheme "" (main.go:127)
2022/09/26 16:09:18 ***ERROR*** Post "/daily_signin?type=0&timestamp=1664208558": unsupported protocol scheme "" (main.go:146)
2022/09/26 16:09:18 ***ERROR*** Post "/user/detail?uid=0&timestamp=1664208558": unsupported protocol scheme "" (main.go:1[3](https://github.com/gbxh/Fuck163MusicTasks-Action/actions/runs/3129232583/jobs/5078201480#step:4:3)2)
2022/09/26 16:09:18 ***ERROR*** Post "/login/status?timestamp=166[4](https://github.com/gbxh/Fuck163MusicTasks-Action/actions/runs/3129232583/jobs/5078201480#step:4:4)208[5](https://github.com/gbxh/Fuck163MusicTasks-Action/actions/runs/3129232583/jobs/5078201480#step:4:5)58": unsupported protocol scheme "" (main.go:127)
2022/09/2[6](https://github.com/gbxh/Fuck163MusicTasks-Action/actions/runs/3129232583/jobs/5078201480#step:4:6) 16:09:1[8](https://github.com/gbxh/Fuck163MusicTasks-Action/actions/runs/3129232583/jobs/5078201480#step:4:8) ***ERROR*** Post "/daily_signin?type=0&timestamp=1664208558": unsupported protocol scheme "" (main.go:146)
2022/0[9](https://github.com/gbxh/Fuck163MusicTasks-Action/actions/runs/3129232583/jobs/5078201480#step:4:9)/26 16:09:18 ***ERROR*** Post "/user/detail?uid=0&timestamp=1664208558": unsupported protocol scheme "" (main.go:132)`

**Comment by XiaoMengXinX** [comment]
@gbxh 首先不建议使用 Action 运行，若要使用的话请先修改一下 Download bin 步骤中的 url，替换为 latest release

具体位置：https://github.com/XiaoMengXinX/Fuck163MusicTasks-Action/blob/6362df90fc071bee3528d17e69271834eae04435/.github/workflows/blank.yml#L31

**Comment by matocool** [comment]
> @gbxh 首先不建议使用 Action 运行，若要使用的话请先修改一下 Download bin 步骤中的 url，替换为 latest release
> 
> 具体位置：https://github.com/XiaoMengXinX/Fuck163MusicTasks-Action/blob/6362df90fc071bee3528d17e69271834eae04435/.github/workflows/blank.yml#L31

已按照要求，更换为 
Run wget https://github.com/XiaoMengXinX/Fuck163MusicTasks/releases/download/v2.1.7/Fuck163MusicTasks_linux_amd64

机密中增加了  Value 值 并填入了 MUSIC_C也不行，

机密中全部删了，在配置文件填入MUSIC_C也不行，


就是死活读取不到配置文件，一直搞不懂这是为什么。。



麻烦大佬过目下，谢谢

https://github.com/matocool/Fuck163MusicTasks-Action/blob/master/.github/workflows/config.json

https://github.com/matocool/Fuck163MusicTasks-Action/actions/runs/3171443526/jobs/5164899762

![image](https://user-images.githubusercontent.com/83129369/193498980-2ac89645-029d-40c8-93dd-81e3346b3828.png)

![image](https://user-images.githubusercontent.com/83129369/193500069-7292162d-8391-45c9-923d-32f7945645a2.png)
