### ISSUE TITLE
cookie填写格式

### ISSUE THREAD

**Issue by zyx338425** [XiaoMengXinX/Fuck163MusicTasks#3]
"Name": "MUSIC_U",
"Value": "USER_1_MUSIC_U"
请问如何填写，获取的MUSIC_U应该填上面还是下面，登录失败

**Comment by XiaoMengXinX** [comment]
music_u的值填在value里

**Comment by zyx338425** [comment]
没有name那个值吗？我找不到哪段

**Comment by zyx338425** [comment]
"Name":"MUSIC_U","Value":"abcdefg1234567890"

value就是你扫码 或者f12 获取的musicu的值

前面的name不用动

**Comment by ShinChanYucan** [comment]
# 你的网易云 cookie 中 MUSIC_U 项的值（用于下载无损歌曲）
MUSIC_U = YOUR_MUSIC_U
