### ISSUE TITLE
使用 action

### ISSUE THREAD

**Issue by matocool** [XiaoMengXinX/Fuck163MusicTasks#30]
Run ./Fuck163MusicTasks_linux_amd64
  ./Fuck163MusicTasks_linux_amd64
  shell: /usr/bin/bash -e {0}
Error: /0[2](https://github.com/matocool/Fuck163MusicTasks-Action/actions/runs/3169355861/jobs/5161210025#step:4:2) 16:55:[4](https://github.com/matocool/Fuck163MusicTasks-Action/actions/runs/3169355861/jobs/5161210025#step:4:5)0 [ERROR] unexpected end of JSON input (main.go:105)
2022/10/02 16:55:40 [FATAL] 读取配置文件失败，请检查你的 JSON 格式是否正确 (main.go:106)
Error: Process completed with exit code 1.

-----------------------------------------------------------------------------------
JSON 文件我是直接复制例子，并且按要求删除所有注释
在机密里面，设置了自己的 Cookies  跟 Users..............

依然提示配置错误。。

难道要把所有带有注释的配置都填入机密吗

**Comment by matocool** [comment]
已按照要求，到 [Release 页](https://github.com/XiaoMengXinX/Fuck163MusicTasks/releases) 下载最新版的构建，

并且把配置文件重命名为 config.json ，将其与下载的可执行文件放在同一目录

同时按照注释，填入需要修改的内容。

运行依然报错。

2022/10/03 10:03:49 [ERROR] invalid character '{' after array element (main.go:115)
2022/10/03 10:03:49 [FATAL] 读取配置文件失败, 请检查你的 JSON 格式是否正确 (main.go:116)

**Comment by matocool** [comment]
2022/10/03 10:47:14 [INFO] [肥肉变成五花肉] 签到成功 (Android) (main.go:375)
2022/10/03 10:47:14 [INFO] [肥肉变成五花肉] 重复签到 (web/PC) (main.go:383)
2022/10/03 10:47:15 [ERROR] 获取 User[1] 登录状态失败, 请检查 MUSIC_U 是否失效 (main.go:180)

奇怪的是，一直提示失效。。。。

为此我特意修改了密码，获取最新的MUSIC_U...然而一直报错

**Comment by XiaoMengXinX** [comment]
1.这个程序是给音乐人做任务的，请确保你的身份是网易云音乐人再使用
2.单用户配置下出现 `取 User[1] 登录状态失败` 不代表运行失败，原因是你配置文件中多出了一个无效的用户配置，删除即可
