### ISSUE TITLE
本地测试MUSIC_U一直失效。。

### ISSUE THREAD

**Issue by matocool** [XiaoMengXinX/Fuck163MusicTasks#31]
2022/10/03 10:47:14 [INFO] [肥肉变成五花肉] 签到成功 (Android) (main.go:375)
2022/10/03 10:47:14 [INFO] [肥肉变成五花肉] 重复签到 (web/PC) (main.go:383)
2022/10/03 10:47:15 [ERROR] 获取 User[1] 登录状态失败, 请检查 MUSIC_U 是否失效 (main.go:180)

奇怪的是，一直提示失效。。。。

为此我特意修改了密码，获取最新的MUSIC_U...然而一直报错

已参考 #3

![image](https://user-images.githubusercontent.com/83129369/193493649-fcd6d765-5874-4b1f-91b8-575f1319edd7.png)

**Comment by matocool** [comment]
同时，action。

添加了配置文件。

2022/10/03 03:37:35 [FATAL] 读取配置文件失败，请检查你的 JSON 格式是否正确 (main.go:10[6](https://github.com/matocool/Fuck163MusicTasks-Action/actions/runs/3171380342/jobs/5164769802#step:4:7))

本地测试的话，他还会提示

2022/10/03 11:33:31 [INFO] [肥肉变成五花肉] 签到成功 (Android) (main.go:375)
2022/10/03 11:33:32 [INFO] [肥肉变成五花肉] 重复签到 (web/PC) (main.go:383)
2022/10/03 11:33:32 [ERROR] 获取 User[1] 登录状态失败, 请检查 MUSIC_U 是否失效 (main.go:180)


机密那边暂时只填入了 Value 的值。其余都是在配置文件直接修改。但是action就是一直读不出来。

**Comment by XiaoMengXinX** [comment]
1.这个程序是给音乐人做任务的，请确保你的身份是网易云音乐人再使用
2.单用户配置下出现 `获取 User[1] 登录状态失败` 不代表运行失败，原因是你配置文件中多出了一个无效的用户配置，删除即可

**Comment by XiaoMengXinX** [comment]
这个状态是运行成功了的，但因为你不是音乐人所以无法继续做其他任务了

**Comment by matocool** [comment]
> 这个状态是运行成功了的，但因为你不是音乐人所以无法继续做其他任务了

原来如此谢谢大佬，我今天刚刚申报的音乐人。然后我顺便把无效的配置删掉试试。谢谢
