### ISSUE TITLE
在自己动态下发布评论无法完成

### ISSUE THREAD

**Issue by Reiice** [XiaoMengXinX/Fuck163MusicTasks#36]
[`config.json`](https://github.com/XiaoMengXinX/Fuck163MusicTasks/blob/master/config_example.json)中没有配置每日任务「在自己动态下发布评论」，是只能手动完成吗？
```bash
2023/02/24 21:04:40 [INFO] [Reiice] 任务「在自己动态下发布评论」任务未完成或进行中 (main.go:641)
```

**Comment by XiaoMengXinX** [comment]
@Reiice 没写这个任务，当初写这个东西的时候还没有这个任务呢（

**Comment by Reiice** [comment]
明白了，那有考虑更新吗？

**Comment by XiaoMengXinX** [comment]
@Reiice 暂时没有（

**Comment by Reiice** [comment]
thx
