### ISSUE TITLE
老哥这个青龙面板可以用的吗，还有就是你这文案有些地方有空格没有说完整呀，能弄一个完整点的教程吗，主要是真不会哈，如果有教程就很棒

### ISSUE THREAD

**Issue by QQ1944591937** [XiaoMengXinX/Fuck163MusicTasks#4]

**Comment by QQ1944591937** [comment]
可能我太小白了吧，啥也不会

**Comment by XiaoMengXinX** [comment]
青龙面板的话，只要是linux/windows系统都可以用，不过还是建议在ssh里用screen挂后台，后续会考虑添加部署到vercel之类平台的教程

**Comment by XiaoMengXinX** [comment]
关于使用方法，只需要按照readme中json的注释，将你的参数填入examole_config.json中即可，如果有不懂的地方可以加tg群 https://t.me/Music163bot_group 交流

**Comment by XiaoMengXinX** [comment]
后续会完善详细教程
