### ISSUE TITLE
可以云函数吗？

### ISSUE THREAD

**Issue by hexin1314** [XiaoMengXinX/Fuck163MusicTasks#5]

**Comment by XiaoMengXinX** [comment]
没试过，按理说可以，等假期考虑适配下（

**Comment by daysplume** [comment]
我有云函数，但最近开始登录失败了

**Comment by XiaoMengXinX** [comment]
看了下文档，应该可以，后续会考虑加入云函数支持

**Comment by XiaoMengXinX** [comment]
https://github.com/XiaoMengXinX/Fuck163MusicTasks/issues/15#issuecomment-1046052370
