### ISSUE TITLE
二维码识别不了

### ISSUE THREAD

**Issue by shaohua-debug** [XiaoMengXinX/Fuck163MusicTasks#7]
![435b4cbf2f3323a325bb074c4d00efc](https://user-images.githubusercontent.com/41368732/147711995-c9b8d2f7-3e27-4fa5-ae7c-820fe0df4bcf.png)
问一下各位大佬，这玩意识别不出来有啥法么？

**Comment by XiaoMengXinX** [comment]
换用标准终端，windows 可以用 windows terminal，另外直接从浏览器拿cookie也可以

**Comment by shaohua-debug** [comment]
> 换用标准终端，windows可以用windows终端，另外直接从浏览器拿cookie也可以
ok，谢谢

**Comment by shaohua-debug** [comment]
> 换用标准终端，windows 可以用 windows terminal，另外直接从浏览器拿cookie也可以

再麻烦问一下
![image](https://user-images.githubusercontent.com/41368732/147723892-a6d22c0e-f305-49d0-8e21-daaad881f894.png)
![image](https://user-images.githubusercontent.com/41368732/147723904-61cba1b8-0e90-47a2-8fa0-4fc03cabc28c.png)
浏览器抓的报错，是这么填写的吗？是MUSIC_U=***；还是***；要加分好或者MUSIC_U=吗？

**Comment by XiaoMengXinX** [comment]
Name 是 MUSIC_U
Value 填写图片中176开头的字符串

**Comment by XiaoMengXinX** [comment]
example: 
`{
    "Name": "MUSIC_U",
    "Value": "1234567890abcdefg"
}`

**Comment by shaohua-debug** [comment]
> example: `{ "Name": "MUSIC_U", "Value": "1234567890abcdefg" }`

谢谢

**Comment by ShinChanYucan** [comment]
# 你的网易云 cookie 中 MUSIC_U 项的值（用于下载无损歌曲）
MUSIC_U = YOUR_MUSIC_U
